### DISCUSSION TITLE
orion.core.worker.algo_wrappers.insist_suggest::Unable to sample a new trial from the algorithm, even after 100 attempts! Returning an empty list.

### DISCUSSION THREAD

**Discussion by cometta** [Epistimio/orion#1102] [General]
may i know error

```
2023-06-26 01:10:04,933::WARNING::orion.core.worker.algo_wrappers.insist_suggest::Unable to sample a new trial from the algorithm, even after 100 attempts! Returning an empty list.
```

when using hyperdad, i use default max_trials, which is very huge number, is the above error due to I use the default max_trials instead of setting small number?

**Comment by bouthilx** [comment]
It may be due to the search space which is too small, so the algorithm keep sample duplicates. Can you please share your configuration, with search space and algorithm configuration?

**Comment by cometta** [comment]
```
experiment:
    algorithm:
        hyperband:
            seed: 1234
            repetitions: 1
evc:
    enable: True
    algorithm_change: True
    auto_resolution: True
    cli_change_type: break
    code_change_type: break
    config_change_type: break
    orion_version_change: False
    ignore_code_changes: False
    manual_resolution: False
    non_monitored_arguments: []
```

command is below, i masked real option names

```
orion hunt -n find_best_parameters_hyperparameter --config orion_config.yaml python do_something.py --optimizer~"choices(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L','M','N','O', 'P', 'Q', 'R', 'S'])" --noise_factors~"choices(['option-1','option-2'])" --noise_amplifier~"choices(['one', 'two', 'three', 'four'])" --extrapolator~"choices(['one', 'two', 'three','four'])" --maxiter~"fidelity(1, 100,base=2)" 
```
