### ISSUE TITLE
Update Storage doc config example

### ISSUE THREAD

**Issue by Delaunay** [Epistimio/orion#1055]
Update doc

```
storage:
  database:
    host: orion_db.pkl
    type: pickleddb
    ```

instead of

```
database:
  host: orion_db.pkl
  type: pickleddb
 ```
 
 
 https://orion.readthedocs.io/en/stable/user/config.html#full-example-of-global-configuration
