### ISSUE TITLE
Configuration in working-dir is empty

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#394]
**Describe the bug**
I specified a working-dir to orion hunt and it creates subfolders for the trials, each with two files `results_*.log` and `trial_*.conf`. 
After a trial is completed the corresponding results file contains the result, but the configuration file remains empty.

**Expected behavior**
The configuration file should contain the trial's hyperparameter configuration.

**Steps to reproduce**
Call `orion hunt` with the `--working-dir` argument.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: e.g. 3.6.9
 - Oríon version: develop
 - Database: PickleDB

**Comment by Thomsch** [comment]
Thanks for opening this issue! We'll fix this ASAP.

**Comment by bouthilx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configuration in working-dir is empty](https://trello.com/c/vuNerTEl/565-configuration-in-working-dir-is-empty)

**Comment by bouthilx** [comment]
Hi Vincent, I'm trying to reproduce this issue without success so far. Could you please share your script configuration?

**Comment by Thomsch** [comment]
> Hi Vincent, I'm trying to reproduce this issue without success so far. Could you please share your script configuration?

@vmichals

**Comment by vmichals** [comment]
Hey, sorry I missed the notification! I believe it was this configuration:
``` 
experiment:
    algorithms: 
        asha:
            seed: null
            num_rungs: null
            num_brackets: 4
    strategy: StubParallelStrategy
```
