### ISSUE TITLE
Debug user_script_config

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#469]
@JSGrondin tried to set the option user_script_config in his local config with:
```
storage:
  database:
    type: 'pickleddb'
    name: 'orion_test'
    host: '/content/gdrive/My Drive/SSD Tutorial/orion_db/save.pkl'
experiment:
  algorithms: 
    asha:
      seed: 0
      num_rungs: null
      num_brackets: 1
  strategy: StubParallelStrategy
worker:
  user_script_config: 'hyp'
```

and commandline call:

```
orion -v hunt -n test21 --config '../orion_db.yaml' python train.py --hyp '../orion_hyp_config.yaml' --img 512 --batch 14 --data '../cgmu_yolo.yaml' --cfg ../yolov5s.yaml --name yolov5s_results --weights yolov5s.pt --cache --logdir '../logs' --epochs~'fidelity(low=1,high=4,base=2)'
```

But the --config argument was not replaced properly with --hyp by Oríon. After investigating it seemed like Oríon did not read the worker.user_script_config argument at all. We need to debug to understand why.
