### ISSUE TITLE
TPE stuck during suggest()

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#679]
@mgermain reported 2 cases where TPE apparently got stuck after as few as 30 trials. Last log line was `DEBUG::orion.core.worker.producer::### Algorithm suggests new points.` and nothing else was logged for hours. The search space was small, limited to about 300 points:
```python
{
    'x': 'choices(["vgg16", "mobilenet_v2", "mobilenet_v3_large", "mobilenet_v3_small"])',
    'y': 'loguniform(1e-5, 1e-1, precision=1)'
}
```

Needs to be reproduced and investigated.

**Comment by bouthilx** [comment]
Reproduced by running 6 workers in parallel with the following setup.

### config.yaml
```yaml
storage:
    database:
        type: 'pickleddb'
        host: 'blog.pkl'

experiment:
    name: 'test'
    max_trials: 500
    algorithms: 'tpe'
```

### script_config.yaml
```
x: 'orion~choices(["vgg16", "mobilenet_v2", "mobilenet_v3_large", "mobilenet_v3_small"])'
y: 'orion~loguniform(1e-5, 1e-1, precision=1)'
```

### script.py
```
import argparse

from orion.client import report_objective

parser = argparse.ArgumentParser()
parser.add_argument("--config", type=str)
inputs = parser.parse_args()

with open(inputs.config, "r") as f:
    import yaml

    config = yaml.load(f)
    import pprint

    pprint.pprint(config)

report_objective(1 - config["y"])
```

### Commandline call
```
$ orion -vvv hunt -c config.yaml python script.py --config script_config.yaml
```
