### ISSUE TITLE
NotImplementedError: Could not find implementation of BaseAlgorithm, type = 'bayesianoptimizer'

### ISSUE THREAD

**Issue by fpaissan** [Epistimio/orion#756]
Hi,

first of all, congrats on the really cool work. I am trying to set up Orion with Bayesian optimization, however, I get the following error:

```
NotImplementedError: Could not find implementation of BaseAlgorithm, type = 'bayesianoptimizer'
Currently, there is an implementation for types:
['asha', 'evolutiones', 'gridsearch', 'hyperband', 'random', 'tpe']
```

To avoid introducing naive errors, I reproduced the [scikit-learn example](https://mila.quebec/en/article/improved-deep-learning-workflows-through-hyperparameter-optimization-with-orion/) on Google Colab and then I tried adding the BayesianOptimizer following these steps:

- `!pip install orion orion.algo.skopt`
- `!orion --debug hunt --config config.yaml python file.py --lr~'loguniform(0.0001, 0.1)'`

However, I get the same error that I have on my local machine.

**Expected behavior**
Start HPO with the Bayesian Optimizer.

**Environment (please complete the following information):**
 - Google Colab, last Orion version

**Additional context**
To help reproducing the issue, I hereby attach the files uploaded in the colab session.

*file.py* - from the tutorial
```
import argparse
 
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
 
# Parsing the value for the hyper-parameter 'learning_rate' 
# given as a command line argument.
parser = argparse.ArgumentParser()
parser.add_argument('--lr', type=float)
inputs = parser.parse_args()
 
# Loading the iris dataset and splitting it into training and testing sets.
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=1)
 
# Training the model with the training set with the specified hyperparameters.
clf = MLPClassifier(learning_rate_init=inputs.lr)
 
clf.fit(X_train, y_train)
 
# Evaluating the accuracy using the testing set.
accuracy = clf.score(X_test, y_test)
 
from orion.client import report_objective
report_objective(1 - accuracy)
```

*config.yaml*
```
storage:
    database:
        type: 'pickleddb'
        host: 'blog.pkl'
 
experiment:
    name: bla
    algorithms:
        BayesianOptimizer:
            seed: null
            n_initial_points: 10
            acq_func: gp_hedge
            alpha: 1.0e-10
            n_restarts_optimizer: 0
            noise: "gaussian"
            normalize_y: False
```

Thanks in advace!

Best,
Francesco.
